# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import newsbox.models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    replaces = [(b'newsbox', '0001_initial'), (b'newsbox', '0002_auto_20160729_2140'), (b'newsbox', '0003_auto_20160730_0441'), (b'newsbox', '0004_auto_20160730_0442')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('uid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
                ('changed', unixtimestampfield.fields.UnixTimeStampField()),
                ('comment', models.IntegerField()),
                ('promote', models.BooleanField()),
                ('moderate', models.BooleanField()),
                ('sticky', models.BooleanField()),
                ('tnid', models.IntegerField()),
                ('translate', models.BooleanField()),
            ],
            options={
                'db_table': 'node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeRevisions',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('teaser', models.TextField()),
                ('log', models.TextField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('format', models.IntegerField()),
            ],
            options={
                'db_table': 'node_revisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeAccess',
            fields=[
                ('node', models.OneToOneField(db_column=b'nid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='access', serialize=False, to='newsbox.Node')),
                ('gid', models.IntegerField()),
                ('realm', models.CharField(max_length=255)),
                ('grant_view', models.SmallIntegerField(choices=[(0, False), (1, True)])),
                ('grant_update', models.SmallIntegerField(choices=[(0, False), (1, True)])),
                ('grant_delete', models.SmallIntegerField(choices=[(0, False), (1, True)])),
            ],
            options={
                'db_table': 'node_access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('type', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('help', models.TextField()),
                ('has_title', models.SmallIntegerField()),
                ('title_label', models.CharField(max_length=255)),
                ('has_body', models.SmallIntegerField()),
                ('body_label', models.CharField(max_length=255)),
                ('min_word_count', models.SmallIntegerField()),
                ('custom', models.SmallIntegerField()),
                ('modified', models.SmallIntegerField()),
                ('locked', models.SmallIntegerField()),
                ('orig_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'node_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlAlias',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=128)),
                ('dst', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=64)),
                ('delta', models.PositiveSmallIntegerField()),
                ('weight', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'filters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilterFormat',
            fields=[
                ('format', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roles', models.CharField(max_length=255)),
                ('cache', newsbox.models.BooleanSmallIntField()),
            ],
            options={
                'db_table': 'filter_formats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('block', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('title',),
                'db_table': 'aggregator_category',
                'managed': False,
                'verbose_name_plural': 'News categories',
            },
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('refresh', models.IntegerField()),
                ('checked', unixtimestampfield.fields.UnixTimeStampField()),
                ('link', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('etag', models.CharField(max_length=255)),
                ('modified', unixtimestampfield.fields.UnixTimeStampField()),
                ('block', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'aggregator_feed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('guid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregator_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeRev',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('teaser', models.TextField(blank=True)),
                ('log', models.TextField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
            ],
            options={
                'default_permissions': (),
                'db_table': 'node_revisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('vid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.SmallIntegerField()),
                ('language', models.CharField(max_length=12)),
                ('trid', models.IntegerField()),
            ],
            options={
                'db_table': 'term_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TermNode',
            fields=[
                ('vid', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'term_node',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='urlalias',
            options={'managed': False, 'verbose_name': 'URL Alias', 'verbose_name_plural': 'URL Aliases'},
        ),
        migrations.CreateModel(
            name='NewsFeedCategory',
            fields=[
                ('feed', models.ForeignKey(db_column=b'fid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='newsbox.NewsFeed')),
            ],
            options={
                'db_table': 'aggregator_category_feed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoryLink',
            fields=[
                ('rev', models.OneToOneField(db_column=b'vid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='story_link', serialize=False, to='newsbox.NodeRev')),
                ('url', models.URLField(blank=True, db_column=b'field_story_url_url', max_length=2048, null=True)),
                ('title', models.CharField(blank=True, db_column=b'field_story_url_title', max_length=2048, null=True)),
                ('attrs', models.TextField(blank=True, db_column=b'field_story_url_attributes', null=True)),
            ],
            options={
                'db_table': 'content_type_story',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TermHierarchy',
            fields=[
                ('term', models.OneToOneField(db_column=b'tid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hier', serialize=False, to='newsbox.Term')),
            ],
            options={
                'db_table': 'term_hierarchy',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='urlalias',
            table='url_alias',
        ),
    ]
