# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('block', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'aggregator_category',
                'managed': False,
                'verbose_name_plural': 'News categories',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('refresh', models.IntegerField()),
                ('checked', unixtimestampfield.fields.UnixTimeStampField()),
                ('link', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('etag', models.CharField(max_length=255)),
                ('modified', unixtimestampfield.fields.UnixTimeStampField()),
                ('block', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'aggregator_feed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('guid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aggregator_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedCategory',
            fields=[
                ('feed', models.ForeignKey(db_column=b'fid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.Feed')),
            ],
            options={
                'db_table': 'aggregator_category_feed',
                'managed': False,
            },
        ),
    ]
