# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False, 'ordering': ('-timestamp',)},
        ),
    ]
