# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=64)),
                ('delta', models.PositiveSmallIntegerField()),
                ('weight', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'filters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilterFormat',
            fields=[
                ('format', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roles', models.CharField(max_length=255)),
                ('cache', lib.models.BooleanSmallIntField()),
            ],
            options={
                'db_table': 'filter_formats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('uid', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
                ('created', unixtimestampfield.fields.UnixTimeStampField()),
                ('changed', unixtimestampfield.fields.UnixTimeStampField()),
                ('comment', models.PositiveIntegerField()),
                ('promote', lib.models.BooleanIntField()),
                ('moderate', lib.models.BooleanIntField()),
                ('sticky', lib.models.BooleanIntField()),
                ('translate', lib.models.BooleanIntField()),
            ],
            options={
                'default_permissions': (),
                'db_table': 'node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeRev',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('teaser', models.TextField(blank=True)),
                ('log', models.TextField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
            ],
            options={
                'default_permissions': (),
                'db_table': 'node_revisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('type', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('help', models.TextField()),
                ('has_title', lib.models.BooleanSmallIntField()),
                ('title_label', models.CharField(max_length=255)),
                ('has_body', lib.models.BooleanSmallIntField()),
                ('body_label', models.CharField(max_length=255)),
                ('min_word_count', models.PositiveSmallIntegerField()),
                ('custom', models.PositiveSmallIntegerField()),
                ('modified', lib.models.BooleanSmallIntField()),
                ('locked', lib.models.BooleanSmallIntField()),
                ('orig_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'node_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeAccess',
            fields=[
                ('node', models.OneToOneField(db_column=b'nid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='access', serialize=False, to='nodes.Node')),
                ('gid', models.PositiveIntegerField()),
                ('realm', models.CharField(max_length=255)),
                ('grant_view', lib.models.BooleanSmallIntField()),
                ('grant_update', lib.models.BooleanSmallIntField()),
                ('grant_delete', lib.models.BooleanSmallIntField()),
            ],
            options={
                'db_table': 'node_access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoryLink',
            fields=[
                ('rev', models.OneToOneField(db_column=b'vid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='story_link', serialize=False, to='nodes.NodeRev')),
                ('url', models.URLField(blank=True, db_column=b'field_story_url_url', max_length=2048, null=True)),
                ('title', models.CharField(blank=True, db_column=b'field_story_url_title', max_length=2048, null=True)),
                ('attrs', models.TextField(blank=True, db_column=b'field_story_url_attributes', null=True)),
            ],
            options={
                'db_table': 'content_type_story',
                'managed': False,
            },
        ),
    ]
