# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import lib.models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('url_md5', lib.models.FixedCharField(max_length=32)),
                ('url', models.TextField()),
                ('link_title', models.CharField(max_length=255)),
                ('last_click_time', unixtimestampfield.fields.UnixTimeStampField()),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinksNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'link_title', max_length=255)),
                ('weight', models.SmallIntegerField()),
                ('clicks', models.IntegerField()),
                ('module', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'links_node',
                'managed': False,
            },
        ),
    ]
