# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_link_linksnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLink',
            fields=[
                ('link', models.ForeignKey(db_column=b'lid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nodelinks', serialize=False, to='nodes.Link')),
                ('title', models.CharField(db_column=b'link_title', max_length=255)),
                ('weight', models.SmallIntegerField()),
                ('clicks', models.IntegerField()),
                ('module', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'links_node',
                'managed': False,
            },
        ),
    ]
